import type { DeployManifest } from "./manifest.js";

const SOLIDITY_IDENT = /^[A-Za-z_]\w*$/;

/**
 * Derive a valid Solidity library identifier from a game name. The raw name may
 * contain hyphens, spaces, or other punctuation (e.g. `my-game`), which would
 * yield an invalid identifier if naively capitalized (`My-gameTables`). We split
 * on any non-alphanumeric run, PascalCase each segment, join them, and append
 * `Tables` (e.g. `my-game` → `MyGameTables`). The result is validated against
 * `/^[A-Za-z_]\w*$/`; an empty or all-punctuation name throws a clear error.
 *
 * Shared by @nexus/core's generator and the CLI's file naming so both agree.
 */
export function solidityLibraryName(name: string): string {
  const pascal = name
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1))
    .join("");
  const lib = `${pascal}Tables`;
  if (!pascal || !SOLIDITY_IDENT.test(lib)) {
    throw new Error(
      `Cannot derive a valid Solidity library name from game name ${JSON.stringify(
        name,
      )}: produced ${JSON.stringify(lib)}, which is not a valid identifier (/^[A-Za-z_]\\w*$/). Use a name with at least one alphanumeric character.`,
    );
  }
  return lib;
}

/**
 * Generate a Solidity tables library for a game from its manifest. The library
 * exposes each table's id constant and a typed struct mirroring the schema, so
 * systems read/write strongly-typed records instead of raw storage.
 *
 * This is intentionally a string generator (no AST) — the output is committed
 * to the game's src/ and compiled by Foundry alongside hand-written systems.
 */
export function generateSolidityTables(manifest: DeployManifest): string {
  const lib = solidityLibraryName(manifest.name);

  const structs = manifest.tables
    .map((tbl) => {
      const fields = tbl.fields.map((f) => `        ${f.solidityType} ${f.name};`).join("\n");
      return `    struct ${tbl.name}Row {\n${fields}\n    }`;
    })
    .join("\n\n");

  const ids = manifest.tables
    .map((tbl) => `    bytes32 internal constant ${tbl.name}_ID = ${tbl.id};`)
    .join("\n");

  const systemIds = manifest.systems
    .map((s) => `    bytes32 internal constant ${s.name}_ID = ${s.id};`)
    .join("\n");

  return `// SPDX-License-Identifier: MIT
// AUTO-GENERATED by @nexus/core from defineGame("${manifest.name}"). Do not edit by hand.
pragma solidity ^0.8.23;

library ${lib} {
    // ── table ids ──
${ids}

    // ── system ids ──
${systemIds}

    // ── row structs ──
${structs}
}
`;
}
