import type { DeployManifest } from "./manifest.js";

/**
 * Generate a Solidity tables library for a game from its manifest. The library
 * exposes each table's id constant and a typed struct mirroring the schema, so
 * systems read/write strongly-typed records instead of raw storage.
 *
 * This is intentionally a string generator (no AST) — the output is committed
 * to the game's src/ and compiled by Foundry alongside hand-written systems.
 */
export function generateSolidityTables(manifest: DeployManifest): string {
  const pascal = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
  const lib = `${pascal(manifest.name)}Tables`;

  const structs = manifest.tables
    .map((tbl) => {
      const fields = tbl.fields.map((f) => `        ${f.solidityType} ${f.name};`).join("\n");
      return `    struct ${tbl.name}Row {\n${fields}\n    }`;
    })
    .join("\n\n");

  const ids = manifest.tables
    .map((tbl) => `    bytes32 internal constant ${tbl.name}_ID = ${tbl.id};`)
    .join("\n");

  const systemIds = manifest.systems
    .map((s) => `    bytes32 internal constant ${s.name}_ID = ${s.id};`)
    .join("\n");

  return `// SPDX-License-Identifier: MIT
// AUTO-GENERATED by @nexus/core from defineGame("${manifest.name}"). Do not edit by hand.
pragma solidity ^0.8.23;

library ${lib} {
    // ── table ids ──
${ids}

    // ── system ids ──
${systemIds}

    // ── row structs ──
${structs}
}
`;
}
